
# -*- coding: utf-8 -*-
"""TesteTrabalho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VLGkYoOdVmC3DQ5PhqpvEWwqwXRcan4p
"""

#1) Dado a sequência de Fibonacci, onde se inicia por 0 e 1 e o próximo valor sempre será a soma dos 2 valores anteriores
#(exemplo: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...), escreva um programa na linguagem que desejar onde, informado um número, ele
#calcule a sequência de Fibonacci e retorne uma mensagem avisando se o número informado pertence ou não a sequência.


def PertenceAFibonacci(Numero):
    if Numero < 0:
        return False

    a, b = 0, 1
    while a <= Numero:
        if a == Numero:
            return True
        a, b = b, a + b
    return False

#Pede ao usuário para inserir um número
NumeroInformado = int(input("Informe um número: "))

#Verifica se o número pertence à sequência de Fibonacci
if PertenceAFibonacci(NumeroInformado):
    print(f"O número {NumeroInformado} pertence à sequência de Fibonacci.")
else:
    print(f"O número {NumeroInformado} NÃO pertence à sequência de Fibonacci.")

#2) Escreva um programa que verifique, em uma string, a existência da letra ‘a’, seja maiúscula ou minúscula,
# além de informar a quantidade de vezes em que ela ocorre.#


def ContarLetra(texto):
    TextoMinusculo = texto.lower()  # Converter o texto para letras minúsculas

    #Conta a quantidade de letras 'a'
    Quantidade = TextoMinusculo.count('a')

    #Verifica a existência de 'a'
    Existe = Quantidade > 0

    return Existe, Quantidade

#Solicita ao usuário para inserir uma string
PalavraInformada = input("Digite uma palavra: ")

#Chama a função e obtém o resultado
Existe, Quantidade = ContarLetra(PalavraInformada)

#Exibe os resultados ao usuário
if Existe:
    print(f"A letra 'a' aparece {Quantidade} vezes na palavra.")
else:
    print("A letra 'a' não está presente na palavra.")

##3) Observe o trecho de código abaixo: int INDICE = 12, SOMA = 0, K = 1; enquanto K < INDICE faça { K = K + 1; SOMA = SOMA + K; } imprimir(SOMA);
##Ao final do processamento, qual será o valor da variável SOMA? 77


INDICE = 12
SOMA = 0
K = 1

while K < INDICE:
    K = K + 1
    SOMA = SOMA + K

print(SOMA)

"""4) Descubra a lógica e complete o próximo elemento:

a) 1, 3, 5, 7, 9

b) 2, 4, 8, 16, 32, 64, 128

c) 0, 1, 4, 9, 16, 25, 36, 49

d) 4, 16, 36, 64, 100

e) 1, 1, 2, 3, 5, 8, 13

f) 2,10, 12, 16, 17, 18, 19, 20

#GABARITO
a) 9

b) 128

c) 49

d) 100

e) 13

f) 20

5) Você está em uma sala com três interruptores, cada um conectado a uma lâmpada em salas diferentes. Você não pode ver as lâmpadas da sala em que está, mas pode ligar e desligar os interruptores quantas vezes quiser. Seu objetivo é descobrir qual interruptor controla qual lâmpada. Como você faria para descobrir, usando apenas duas idas até uma das salas das lâmpadas, qual interruptor controla cada lâmpada?


1. Ligar o primeiro interruptor (Interruptor A) e deixar ligado por cerca de 15 minutos. A lâmpada que é ligada pelo interruptor "A" esquentará.

2. Desligar o primeiro interruptor (Interruptor A) e  ligar o segundo interruptor (Interruptor B).

3. Ir nas salas.

A lâmpada acesa é controlada pelo Interruptor B, pois ele está ligado no momento.

A lâmpada apagada, mas que estiver quente essa é controlada pelo Interruptor A.

A lâmpada apagada e fria essa é controlada pelo Interruptor C.
"""